import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Deddy W",
  description: "Generated by create next app",
};

const headerLinks = [
  {
    label: "About",
    href: "#about",
  },
  {
    label: "Work",
    href: "#work",
  },
  {
    label: "Blog",
    href: "#blog",
  },
];

const footerLinks = [
  {
    label: "x.com @deddywolley",
    href: "https://x.com/@deddywolley",
  },
  {
    label: "IG @deddywolley",
    href: "https://www.instagram.com/deddywolley/",
  },
  {
    label: "linkedin",
    href: "https://www.linkedin.com/in/deddy-wolley-b09ab312a/",
  },
  {
    label: "github",
    href: "https://github.com/philldev",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} antialiased min-h-screen text-foreground bg-background`,
          "font-mono font-light",
          "text-sm md:text-base",
        )}
      >
        <div className="fixed h-screen w-screen inset-0 bg-gradient-to-b from-slate-950/20 to-amber-950/20" />
        <div className="fixed h-screen w-screen inset-0 bg-gradient-to-br from-blue-950/10 to-slate-950/10" />
        <header className="h-16 border-b border-grid sticky top-0 bg-background/50 backdrop-blur z-10">
          <div className="max-w-5xl mx-auto w-full h-full flex items-center justify-between gap-4 lg:border-x border-grid md:px-10 px-4">
            <span className="tracking-widest font-bold">DEDDY W.</span>
            <div className="flex items-center gap-4 text-muted-foreground">
              {headerLinks.map((link) => (
                <div key={link.label}>
                  <Link shallow={false} href={link.href}>
                    {link.label}
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </header>
        <main className="max-w-5xl w-full mx-auto lg:border-x border-grid px-4 md:px-10 relative pb-20">
          {children}
        </main>
        <footer className="border-t border-grid">
          <ul className="max-w-5xl py-4 w-full mx-auto flex items-center gap-4 lg:border-x border-grid px-4 md:px-10 h-full text-xs flex-col md:flex-row">
            {footerLinks.map((link) => (
              <li key={link.label}>
                <Link shallow={false} href={link.href}>
                  {link.label}
                </Link>
              </li>
            ))}
          </ul>
        </footer>
      </body>
    </html>
  );
}
